### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Heidi-19#1]
Sintesis de cálidad 
[Sintesis_gestion en calidad de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Heidi-19/files/12704223/Sintesis_gestion.en.calidad.de.proyectos.de.software.pdf)

**Comment by Gregorio012** [comment]
Calf: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
